baseURL: https://almalinux.org
locale: en-us
title: AlmaLinux
disableKinds:
  - taxonomy

pagination:
  pagerSize: 15

taxonomies:
  author: authors
  about-author: about-authors
  image: images

defaultContentLanguage: en
languages:
  en: { weight: 1, label: English }
  ar: { weight: 2, label: العربية, direction: rtl }
  ca: { weight: 2, label: Català }
  cs: { weight: 2, label: Česky }
  da: { weight: 2, label: Dansk }
  de: { weight: 2, label: Deutsch }
  el: { weight: 2, label: Ελληνικά }
  es: { weight: 2, label: Español }
  fa: { weight: 2, label: فارسى }
  fi: { weight: 2, label: Suomi }
  fr: { weight: 2, label: Français }
  he: { weight: 2, label: עברית, direction: rtl }
  hu: { weight: 2, label: magyar }
  it: { weight: 2, label: Italiano }
  ja: { weight: 2, label: 日本語 }
  ko: { weight: 2, label: 한국어 }
  lt: { weight: 2, label: Lietuvių }
  lv: { weight: 2, label: latviešu }
  pl: { weight: 2, label: Polski }
  pt: { weight: 2, label: Português }
  pt-br: { weight: 2, label: Português Brasileiro }
  ru: { weight: 2, label: Русский }
  sk: { weight: 2, label: Slovensky }
  sv: { weight: 2, label: svenska }
  tr: { weight: 2, label: Türkçe }
  uk: { weight: 2, label: Українська }
  zh-hans: { weight: 2, label: 简体中文 }

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    noClasses: true
    style: xcode-dark

outputs:
  home:
    - HTML
    - JSON
