# Docker image for production environment.
# You should NOT publish this image.

FROM almalinux/almalinux:8

RUN groupadd -g 900 web && \
    useradd -d /app -M -r -s /bin/bash web -g 900 -u 900

COPY tmp/deploy /app

# We don't need any static files inside this image
RUN rm -rf /app/public/*

RUN chown web:web -Rf /app

WORKDIR /app

RUN dnf -y install \
    gcc \
    make \
    gettext \
    python38 \
    python38-devel \
    mariadb-devel

RUN su - web -c 'pip3 install -r requirements.txt --user'

# Use our local env
ENV PYTHONPATH=/app/.local/lib/python3.8/site-packages:$PYTHONPATH
ENV PATH=/app/.local/bin:$PATH

# Cleanup
RUN dnf -y remove gcc \
    && dnf -y clean all \
    && rm -rf /var/cache/yum

CMD su web -c 'make uwsgi'
