version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      args:
        LOCAL_UID: ${LOCAL_UID}
        LOCAL_GID: ${LOCAL_GID}
    restart: 'no'
    links:
      - mariadb
      - frontend
    volumes:
      - .:/app/
    ports:
      - 8080:8080 # HTTP

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
      args:
        LOCAL_UID: ${LOCAL_UID}
        LOCAL_GID: ${LOCAL_GID}
    restart: 'no'
    volumes:
      - .:/app/
    ports:
      - 8090:8090 # HTTP devserver

  mariadb:
    image: mariadb:10
    container_name: mariadb
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: devel
      MYSQL_DATABASE: devel
      MYSQL_USER: devel
      MYSQL_PASSWORD: devel
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mariadb:
    driver: local
