# Docker image for local development environment.
# You should NOT publish this image, it is intended for local use only.

FROM almalinux/almalinux:8
ARG LOCAL_UID
ARG LOCAL_GID
ARG LOCAL_USER=web

RUN groupadd -g $LOCAL_GID -o $LOCAL_USER
RUN useradd -m -u $LOCAL_UID -g $LOCAL_GID -o -s /bin/bash $LOCAL_USER

RUN dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm && \
    dnf -y install yum-utils && \
    curl -fsSL https://rpm.nodesource.com/setup_15.x | bash - && \
    curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo

RUN dnf -y install \
    make \
    gcc-c++ \
    nodejs \
    yarn

WORKDIR /app

CMD make frontend-runserver
