# Generated by Django 3.2.3 on 2021-05-30 13:59

import django.core.validators
from django.db import migrations, models

import commons.uploads


class Migration(migrations.Migration):
    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialSupportVendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Name of the vendor', max_length=100)),
                ('logo', models.FileField(help_text='Logo of the vendor. MUST be a zero-margin SVG file!',
                                          upload_to=commons.uploads.segmented_upload_to,
                                          validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('url', models.URLField(help_text='URL of the vendor')),
                ('priority', models.PositiveIntegerField(default=0,
                                                         help_text='Absolute priority of the vendor relative to other vendors. The higher the priority, the earlier the vendor will appear.')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'),
                                            ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'),
                                            ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'),
                                            ('ru', 'Русский'), ('uk', 'Украї́нська')], db_index=True, default='en',
                                   max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'),
                                            ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'),
                                            ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'),
                                            ('ru', 'Русский'), ('uk', 'Украї́нська')], db_index=True, default='en',
                                   max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'),
                                            ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'),
                                            ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'),
                                            ('ru', 'Русский'), ('uk', 'Украї́нська')], db_index=True, default='en',
                                   max_length=7, verbose_name='Content language'),
        ),
    ]
