# Generated by Django 3.2.3 on 2021-05-30 14:53

from django.db import migrations, models

import commons.uploads


class Migration(migrations.Migration):
    dependencies = [
        ('www', '0002_auto_20210530_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(
                    choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'),
                             ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'),
                             ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'),
                             ('ru', 'Русский'), ('uk', 'Украї́нська')], db_index=True, default='en', max_length=7,
                    verbose_name='Content language')),
                ('title', models.CharField(help_text='Feature title', max_length=255)),
                ('description', models.TextField(help_text='Feature description')),
                ('screenshot',
                 models.ImageField(help_text='Feature screenshot', upload_to=commons.uploads.segmented_upload_to)),
                ('priority', models.PositiveIntegerField(
                    default=0,
                    help_text='Absolute priority of the feature relative to other features. The higher the priority, the earlier the feature will appear.')
                 ),
            ],
        ),
    ]
