# Generated by Django 3.2.3 on 2021-07-25 14:02

import commons.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_showcasefeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Feature image - any web-safe format', upload_to=commons.uploads.segmented_upload_to),
        ),
    ]
