# Generated by Django 3.2.7 on 2021-09-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('www', '0004_add_featured_image_to_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_md',
            field=models.TextField(blank=True, help_text='Markdown content of the blog entry', verbose_name='Content (Markdown)'),
        ),
        migrations.AddField(
            model_name='page',
            name='content_html',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='page',
            name='content_md',
            field=models.TextField(blank=True, help_text='Markdown content of the page content', verbose_name='Content (Markdown)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='showcasefeature',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
    ]
