# Generated by Django 3.2.3 on 2021-08-16 21:50

import commons.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_add_featured_image_to_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernanceMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('board', 'Board'), ('governance_board', 'Governance board')], db_index=True, default='board', max_length=100, verbose_name='Member of the')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=commons.uploads.segmented_upload_to)),
                ('organization', models.CharField(blank=True, help_text='Organization of the member', max_length=255)),
                ('organization_position', models.CharField(blank=True, help_text='Position in the organization', max_length=255)),
                ('about', models.CharField(blank=True, help_text='Short about, if no organization applies etc.', max_length=255)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Absolute priority of the individual in the listing relative to other individuals. The higher the priority, the earlier the feature will appear.')),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='showcasefeature',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
    ]
