# Generated by Django 3.2.7 on 2021-09-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20210912_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
    ]
