# Generated by Django 3.2.7 on 2021-09-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0005_auto_20210816_2150'),
        ('www', '0006_auto_20210912_1334'),
    ]

    operations = [
    ]
