# Generated by Django 3.2.7 on 2021-10-04 20:33
import uuid

import commons.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_merge_0005_auto_20210816_2150_0006_auto_20210912_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='A file to upload (any type)', upload_to=commons.uploads.segmented_upload_to)),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='governancemember',
            name='image',
            field=models.ImageField(help_text='Must be an image with aspect ratio of 1:1, at least 200px * 200px', upload_to=commons.uploads.segmented_upload_to),
        ),
        migrations.AlterField(
            model_name='governancemember',
            name='type',
            field=models.CharField(choices=[('governance_board', 'Board of Directors')], db_index=True, default='governance_board', max_length=100, verbose_name='Member of the'),
        ),
        migrations.AlterField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='showcasefeature',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
    ]
