# Generated by Django 3.2.7 on 2021-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0008_auto_20211004_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOTD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published', models.BooleanField(default=True, help_text='Uncheck to hide')),
                ('text', models.TextField(help_text='Maximum 160 characters', max_length=160)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'MOTD',
                'verbose_name_plural': 'MOTDs',
            },
        ),
    ]
