# Generated by Django 3.2.7 on 2021-10-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_motd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='faqentry',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='page',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
        migrations.AlterField(
            model_name='showcasefeature',
            name='lang',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('he', 'עִבְרִית'), ('it', 'Italiano'), ('ja', '日本語'), ('lv', 'Latviešu'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português Brasileiro'), ('ru', 'Русский'), ('tr', 'Türkçe'), ('uk', 'Украї́нська'), ('zh-hans', 'Chinese (Simplified)')], db_index=True, default='en', max_length=7, verbose_name='Content language'),
        ),
    ]
