---
- name: Make Journal persist logs
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: Storage
    value: persistent
    mode: '0644'
    backup: yes
  notify: ['Restart journald']
  become: yes

- name: Make Journal compress logs
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: Compress
    value: 'true'
    mode: '0644'
    backup: yes
  notify: ['Restart journald']
  become: yes

- name: Make Journal store maximum of 30 days of logs
  ini_file:
    path: /etc/systemd/journald.conf
    section: Journal
    option: MaxRetentionSec
    value: '1month'
    mode: '0644'
    backup: yes
  notify: ['Restart journald']
  become: yes
