---
- name: Ensure group deploy exists
  group:
    name: deploy
    state: present
    gid: 900
  become: yes

- name: Configure deployment user
  user:
    name: deploy
    create_home: yes
    shell: /bin/bash
    groups: docker
    append: yes
    state: present
    uid: 900
  become: yes

- name: Ensure deploy .ssh directory
  file:
    path: /home/deploy/.ssh
    state: directory
    owner: deploy
    group: deploy
    mode: '0700'
  become: yes

- name: Add all authorized keys to deployment user
  template: src='web_authorized_keys.jinja2' dest='/home/deploy/.ssh/authorized_keys' mode='0600' owner=deploy group=deploy
  become: yes
  tags: [ 'users' ]
