---
- name: Ensure deployment directory
  file:
    path: /opt/almalinux.org/
    state: directory
    owner: deploy
    group: deploy
    mode: '0750'
  become: yes

- name: Ensure deployment releases directory
  file:
    path: /opt/almalinux.org/release/
    state: directory
    owner: deploy
    group: deploy
    mode: '0750'
  become: yes

- name: Ensure webroot directory
  file:
    path: /var/www/almalinux.org/
    state: directory
    owner: deploy
    group: nginx
    mode: '0750'
  become: yes

- name: Ensure webroot release deployment directory
  file:
    path: /var/www/almalinux.org/release/
    state: directory
    owner: deploy
    group: nginx
    mode: '0750'
  become: yes

- name: Ensure media uploads directory
  file:
    path: /var/www/almalinux.org/media/
    state: directory
    owner: deploy
    group: nginx
    mode: '0750'
    recurse: true
  become: yes

- name: Check if site SSL cert exists
  stat:
    path: /etc/ssl/almalinux.org.cert.pem
  register: site_cert
  become: yes

- name: Check if site SSL key exists
  stat:
    path: /etc/ssl/almalinux.org.key.pem
  register: site_key
  become: yes

- name: Link site cert to temporary cert if site cert does not exist
  file:
    src: /etc/ssl/selfsigned.crt
    dest: /etc/ssl/almalinux.org.cert.pem
    owner: root
    group: root
    state: link
  become: yes
  when: not site_cert.stat.exists

- name: Link site key to temporary key if site key does not exist
  file:
    src: /etc/ssl/selfsigned.key
    dest: /etc/ssl/almalinux.org.key.pem
    owner: root
    group: root
    state: link
  become: yes
  when: not site_key.stat.exists

- name: Configure almalinux.org vhost
  copy: src='nginx.conf.d/almalinux.org.conf' dest='/etc/nginx/conf.d/almalinux.org.conf' mode='0644' owner=root group=root
  notify: [ 'Reload NGINX' ]
  become: yes
  tags: [ 'www_conf' ]
